export const users = [
   {
      fullName: 'Александров Игнат Анатолиевич',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Шевченко Рафаил Михайлович',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Мазайло Трофим Артёмович',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Логинов Остин Данилович',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Борисов Йошка Васильевич',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Соловьёв Ждан Михайлович',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Негода Михаил Эдуардович',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Гордеев Шамиль Леонидович',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Многогрешный Павел Виталиевич',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Александров Игнат Анатолиевич',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Волков Эрик Алексеевич',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Кузьмин Ростислав Васильевич',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Стрелков Филипп Борисович',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
   {
      fullName: 'Галкин Феликс Платонович',
      numberOfGames: 24534,
      victory: 9824,
      defeat: 1222,
      percent: '87 %',
   },
]